name: Build Debian Package

on:
  # Only build packages on main branch pushes (after PR is merged) or when creating a release
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'doc/**'
  release:
    types: [created]
  workflow_dispatch:  # Allows manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  build-deb:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Debian packaging tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper devscripts

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Make build script executable
      run: chmod +x build.sh
      
    - name: Build Debian package
      run: ./build.sh
      
    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: |
          *.deb
        if-no-files-found: error
